from vector import Vector

print("------------ Vector A ------------")
a = Vector([[1.0, 2.0, 3.0]])
print("- Print: ")
print(a)
print()
print("- Transpose: ")
print(a.T())
print()
print("- Dot A: ")
print(a.dot(a))
print()
print("- A + 2.5: ")
print(a + 2.5)
print()
print("- A + strstr: ")
print(a + "strstr")
print()
print("- A - 2.5: ")
print(a - 2.5)
print()
print("- A - strstr: ")
print(a - "strstr")
print()
print("- A x 2.0: ")
print(a * 2.0)
print()
print("- A * strstr: ")
print(a * "strstr")
print()
print("- A / 2.0: ")
print(a / 2.0)
print()
print("- A / 0: ")
print(a / 0)
print()
print("- A / strstr: ")
print(a / "strstr")
print()
print("- A + A: ")
print(a + a)
print()
print("- A - A: ")
print(a - a)
print()
print("------------ Vector B ------------")
b = Vector([[4.0], [5.0], [6.0]])
print("- Print: ")
print(b)
print()
print("- Transpose: ")
print(b.T())
print()
print("- Dot B: ")
print(b.dot(b))
print()
print("- B + 3.5: ")
print(b + 3.5)
print()
print("- B - 3.5: ")
print(b - 3.5)
print()
print("- B x 1.5: ")
print(b * 1.5)
print()
print("- B / 1.5: ")
print(b / 1.5)
print()
print("- B / 0.0: ")
print(b / 0.0)
print()
print("- B + B: ")
print(b + b)
print()
print("- B - B: ")
print(b - b)
print()