from vector import Vector

print("------------ Vector A [[1.0, 2.0, 3.0]] ------------")
a = Vector([[1.0, 2.0, 3.0]])
print("- Print: ")
print(a)
print("- Transpose: ")
print(a.T())
print("- Dot A: ")
print(a.dot(a))
print("- A + 2.5: ")
print(a + 2.5)
print("- A - 2.5: ")
print(a - 2.5)
print("- A x 2.0: ")
print(a * 2.5)
print("- A / 2.0: ")
print(a / 2.5)
print()
print("------------ Vector B [[4.0], [5.0], [6.0]] ------------")
b = Vector([[4.0], [5.0], [6.0]])
print("- Print: ")
print(b)
print("- Transpose: ")
print(b.T())
print("- Dot B: ")
print(b.dot(b))
print("- B + 3.5: ")
print(b + 3.5)
print("- B - 3.5: ")
print(b - 3.5)